import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/app/authProvider";
import { CssBaseline, ThemeProvider, createTheme } from "@mui/material";
import "@fontsource/playfair-display";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <CssBaseline />
        <body className={inter.className}>{children}</body>
      </AuthProvider>
    </html>
  );
}
